### ISSUE TITLE
[WM] Progress für victory condition ergänzen

### ISSUE THREAD

**Issue by vikpek** [vikpek/BeforeLegendsBeta#13]
Neues Element. 

Fortschritt hin zu der Victory condition. Links oben - unter der Anzeige für Rundenanzahl.
Sliderfunktionalität - wie bei Itemshop - aber auf Click - nicht auf Mousehover.

**Comment by Icii** [comment]
Funktionalität ist drin, hat aber immoment noch nur Platzhaltergrafiken und ist generell noch Unsauber.
Ich lass das Offen, weil ich das noch verfeinern will.
