### ISSUE TITLE
[WM] Ingame Pause Menu

### ISSUE THREAD

**Issue by vikpek** [vikpek/BeforeLegendsBeta#15]
Bei Pause (ESC) soll wieder das Ingame Menu angezeigt werden:
- Pausiertes Game (funktioniert schon)
- Optionen:
  - Return to game
  - Return to main menu
  - Exit to desktop

**Comment by Icii** [comment]
Funktionalität ist drin. Platzierung und evtl andere Grafiken müssen noch gemacht werden.
