### ISSUE TITLE
[WM] Generierung von Map mit weniger großen Flächen

### ISSUE THREAD

**Issue by vikpek** [vikpek/BeforeLegendsBeta#19]

**Comment by Icii** [comment]
Nachdem ich ein wenig mit den Werten rumgespielt habe, hatte ich folgendes Festgestellt:
TemperatureScale und MoistureScale haben minimale Auswirkungen:
Moisture 0: http://imgur.com/Tf3u7eB
Moisture 1000: http://imgur.com/90jAPCd
Temperature 100: http://imgur.com/dAg9iVz
ContinentScale lässt bei vielen Werten Unity abstürzen.

Entweder wir lassen das ganz Weg, warten auf Luke oder die Gamedesigner setzen sich daran und probieren aus, welche Werte am Sinnvollsten sind und in welcher Range die sich bewegen müssen.
