### ISSUE TITLE
Olaf kann nicht weiterlaufen nach einem Kampf

### ISSUE THREAD

**Issue by DerKudi** [vikpek/BeforeLegendsBeta#2]

**Comment by Icii** [comment]
Bug: Im Turnmanager wurde nach einem Kampf die Variable numActions auf -1 gesetzt.
Fix: if(numActions < 0) numActions = 0;
Möglicherweise sollte man ne bessere Möglichkeit finden, zB warum die Variable auf -1 gesetzt wird.
