### ISSUE TITLE
[WM] Dynamisches Feedback für Ressourcensammeln/ausgeben

### ISSUE THREAD

**Issue by vikpek** [vikpek/BeforeLegendsBeta#24]
Wenn sich im Ressourcencount was ändert sollte das mit aufblinkendem Text signalisiert werden.

Links neben der Ressourcen Anzeige fade in/out wie z.B "+1"

**Comment by Icii** [comment]
Ein kleines Minus/Plus poppt kurz an der entsprechenden Stelle auf.
