### ISSUE TITLE
Bewegung während offenem Itemshop

### ISSUE THREAD

**Issue by vikpek** [vikpek/BeforeLegendsBeta#4]
Olaf läuft im Hintergrund hin und her wenn man auf Kaufbutton clickt. Bewegung muss pausiert sein währendessen.

**Comment by Icii** [comment]
Bug: if (UnityEngine.EventSystems.EventSystem.current.IsPointerOverGameObject())
                return;
in dem Script MoveOnClick war auskomentiert.
Fix: Comment entfernen.
Warum war das auskommentiert? Macht das Fehler? Ich konnte keine Finden.
