### ISSUE TITLE
CHEET: turn off FOW

### ISSUE THREAD

**Issue by TomaKomitski** [vikpek/BeforeLegendsBeta#42]
Ich würde gern, dass wir ein CHEET button haben, der beim drücken in game den FOW ausschaltet, damit man verschidene Karten Einstellungen in game schnell beobachten kann.
Danke!

**Comment by Icii** [comment]
Der Button x schaltet jetzt den FoW aus, und setzt alle Gegner + Ressourcen auf Visible.
Es laggt ein wenig, wenn die ganzen Ressourcen runterfallen, geht aber alles in allem.
