### ISSUE TITLE
Center on Olaf Button

### ISSUE THREAD

**Issue by TomaKomitski** [vikpek/BeforeLegendsBeta#43]
wir brauchen ein Knopf der die Kamera auf Olaf zentriert wenn gedrückt, damit man schnell zurück zu Olaf gehen kann nachdem man durch die Map mit der Kamera rumgefahren ist, sonst muss man ihn ewig suchen

**Comment by Icii** [comment]
Auf der WorldCamera, das ScriptMouseMovement hat jetzt eine Variable "backToOlaf". Wenn der festgelegte knopf gedrückt wird (Immoment O), wird die Kamera auf Olaf zentriert.
