### ISSUE TITLE
Random Seed for new map

### ISSUE THREAD

**Issue by TomaKomitski** [vikpek/BeforeLegendsBeta#44]
ich glaube wenn man neue Spiel mit den gleichen stats eingibt in start game wird immer die gleich map generiert, der Random seed soll sich automatisch jedes neues spiel ändern

**Comment by Icii** [comment]
Seed wird jetzt Random berechnet.
Im Script WorldMapGenerator.cs gibt es ein Toggle um Random Ein- und Auszuschalten.
