### ISSUE TITLE
Olaf WM regeneration funktioniert nicht

### ISSUE THREAD

**Issue by TomaKomitski** [vikpek/BeforeLegendsBeta#45]
Wenn Olaf verletzt ist aber genug essen hat, regeneriert er sich trotzdem nicht (WM)

Das hat schon mal funktioniert

**Comment by Icii** [comment]
Bug: Die Variablen im RessourceMaster waren nicht belegt.und UnitInfo Popup wird nicht am Rundenende aktualisiert.
Fix: Werte eintragen + Kleine Änderungen in Scripten, sodass Olaf stirbt bei 0 HP und die HP nicht negativ werden + UnitInfo beim beenden der Runde aktualisieren
