### ISSUE TITLE
Starvation Warnung (Roter Skull UI Feedback) wird nicht angezeigt

### ISSUE THREAD

**Issue by vikpek** [vikpek/BeforeLegendsBeta#7]
Hat schonmal funktioniert.

**Comment by Icii** [comment]
Bug: Prefab fehlte
Fix: Lol

**Comment by TomaKomitski** [comment]
Starvation funktioniert nicht mehr - es wird kein HP verloren, es wird kein schädel angeteigt

**Comment by Icii** [comment]
Der Schädel sollte jetzt angezeigt werden.
Das keine HP verloren/regeneriert werden, liegt wahrscheinlich daran, das im RessourceManager die entsprechenden Variablen nicht belegt sind/auf 0 stehen,
